### ISSUE TITLE
感谢大佬，一遍就安装上了！但是有些小问题。。。

### ISSUE THREAD

**Issue by bk210** [duxphp/Hackintosh-12700KF-B660M-MORTAR-6600XT#2]
但是目前有个小问题，istat这个软件中的温度参数貌似有些小问题，希望有空可以帮忙看下，不胜感激！：

温度未直接显示，以及cpu的线程作为核心显示。
![1648861080901](https://user-images.githubusercontent.com/4556392/161357928-bc352ca9-3f7c-40a8-b764-55d8b5fbdd55.jpg)

再次感谢无私奉献efi！

**Comment by duxphp** [comment]
12代的驱动只能是将小核心和线程做为核心 这里没问题的  目前只有这个方案 
传感器那里也是一样 6系列主板传感器只有这些
